### ISSUE TITLE
Unmaintained and may not work

### ISSUE THREAD

**Issue by wayne530** [Mayur57/twitter-nuke#6]
This project seems to be unmaintained and out of the box did not work for me, including typos in the instructions as pointed out in other issues. I created a much simpler, albeit less robust, NodeJS script including step-by-step instructions for obtaining all keys/tokens, which you may find useful:

https://github.com/wayne530/twitter-wipe

**Comment by mayur57** [comment]
Hello @wayne530, thanks for the feedback and suggestions. Yes, this project has been unmaintained for quite a while due to me being busy. The tool was written for personal use, therefore was hastily written and may be unoptimised and have a few quirks.

I had realised this and decided to open source it so that people could iterate over it. Rest assured the script will be improved with better docs and newer stuff like Twitter API v2, turning it into a web app when I get time to work on it. Great work building your tool by the way, please keep it going!

I'll update the docs to reflect the lack of support till I start pushing updates.

**Comment by ghost** [comment]
I mostly had success with this script, after:

* getting the pip3 command right
* deleting the broken and apparently unneeded demjson requirement (issue #8)
* changing tweet.js to tweets.js in the script

I did get one Python error I noticed (see issue #7). I also had some timeout errors, and some errors from Twitter like  'Sorry, you are not authorized to see this status.' or 'Sorry, that page does not exist.' I was left with a few undeleted tweets presumably due to the above. (Maybe the script could be modified to catch timeouts and re-try a couple of times.) One tweet with a lot of retweets was listed as skipped. I did not change the script but as is it does seem to exempt tweets with >40 retweets, I guess.

I re-ran the script which of course resulted in a lot of 'No status found with that ID.' but did delete most of the tweets missed on the first pass. Aside from the one tweet listed as skipped, there were two other tweets not deleted, both with relatively high (for me) numbers of likes.

**Comment by runna5k** [comment]
> I mostly had success with this script, after:
> 
> * getting the pip3 command right
> * deleting the broken and apparently unneeded demjson requirement (issue [demjson broken and unneeded #8](https://github.com/Mayur57/twitter-nuke/issues/8))
> * changing tweet.js to tweets.js in the script
> 
> I did get one Python error I noticed (see issue #7). I also had some timeout errors, and some errors from Twitter like 'Sorry, you are not authorized to see this status.' or 'Sorry, that page does not exist.' I was left with a few undeleted tweets presumably due to the above. (Maybe the script could be modified to catch timeouts and re-try a couple of times.) One tweet with a lot of retweets was listed as skipped. I did not change the script but as is it does seem to exempt tweets with >40 retweets, I guess.
> 
> I re-ran the script which of course resulted in a lot of 'No status found with that ID.' but did delete most of the tweets missed on the first pass. Aside from the one tweet listed as skipped, there were two other tweets not deleted, both with relatively high (for me) numbers of likes.

Hey Holmes would you mind posting a repo of the code you edited. Id liketo get a fresh copy of ur version and work on maybe making a few optimizations myself

**Comment by ghost** [comment]
It's at https://github.com/holmesrichards/twitter-nuke
